#!/bin/bash
# =============================================================================
# AI Game Engine — 一键新建游戏项目
#
# 用法:
#   ./tools/new_project.sh <项目名> [目标目录]
#
# 示例:
#   ./tools/new_project.sh my_snake_game
#   ./tools/new_project.sh 太空射击 ~/GodotGames
#   ./tools/new_project.sh breakout_game ~/Desktop/games
#
# 功能:
#   1. 在目标目录下创建空 Godot 4 项目
#   2. 符号链接 addons/ai_engine/ 插件（自动同步更新）
#   3. 预启用插件（无需手动在 Project Settings 中勾选）
#   4. 自动用 Godot 打开项目
# =============================================================================

set -e

# ---------------------------------------------------------------------------
# 颜色输出
# ---------------------------------------------------------------------------
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[✗]${NC} $1"; }
step()  { echo -e "${CYAN}[→]${NC} $1"; }

# ---------------------------------------------------------------------------
# 定位脚本所在目录（即 ai-game-engine/tools/）
# ---------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENGINE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ADDON_SOURCE="$ENGINE_ROOT/addons/ai_engine"

# ---------------------------------------------------------------------------
# 参数解析
# ---------------------------------------------------------------------------
PROJECT_NAME="$1"
TARGET_BASE="${2:-$HOME/GodotGames}"

if [ -z "$PROJECT_NAME" ]; then
    echo ""
    echo "🎮 AI Game Engine — 一键新建游戏项目"
    echo ""
    echo "用法: $0 <项目名> [目标目录]"
    echo ""
    echo "参数:"
    echo "  项目名      游戏项目名称（必填）"
    echo "  目标目录    项目存放位置（可选，默认: ~/GodotGames/）"
    echo ""
    echo "示例:"
    echo "  $0 my_snake_game"
    echo "  $0 太空射击 ~/Desktop/games"
    echo "  $0 breakout_game /tmp/test_games"
    echo ""
    exit 1
fi

PROJECT_DIR="$TARGET_BASE/$PROJECT_NAME"

# ---------------------------------------------------------------------------
# 前置检查
# ---------------------------------------------------------------------------

# 检查插件源码
if [ ! -d "$ADDON_SOURCE" ]; then
    error "找不到插件目录: $ADDON_SOURCE"
    error "请确保从 ai-game-engine 仓库的 tools/ 目录下运行此脚本"
    exit 1
fi

# 检查项目是否已存在
if [ -d "$PROJECT_DIR" ]; then
    error "项目目录已存在: $PROJECT_DIR"
    error "如需重新创建，请先删除该目录"
    exit 1
fi

# 检查 Godot 是否安装
GODOT_APP="/Applications/Godot.app"
HAS_GODOT=false
if [ -d "$GODOT_APP" ]; then
    HAS_GODOT=true
else
    warn "未找到 Godot.app，项目将创建但不会自动打开"
    warn "请安装 Godot 4.6+ 后手动打开项目"
fi

# ---------------------------------------------------------------------------
# 创建项目
# ---------------------------------------------------------------------------
echo ""
echo "🎮 AI Game Engine — 新建项目"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

step "创建项目目录: $PROJECT_DIR"
mkdir -p "$PROJECT_DIR/addons"

step "生成 project.godot"
cat > "$PROJECT_DIR/project.godot" << GODOT_CONFIG
; Engine configuration file.
; Generated by AI Game Engine (tools/new_project.sh)

[application]

config/name="$PROJECT_NAME"
config/features=PackedStringArray("4.4")

[display]

window/size/viewport_width=1152
window/size/viewport_height=648

[editor_plugins]

enabled=PackedStringArray("res://addons/ai_engine/plugin.cfg")

[rendering]

renderer/rendering_method="mobile"
GODOT_CONFIG

step "符号链接插件: addons/ai_engine/ → 仓库源码"
ln -s "$ADDON_SOURCE" "$PROJECT_DIR/addons/ai_engine"

info "项目创建完成!"
echo ""
echo "  📁 项目路径: $PROJECT_DIR"
echo "  🔗 插件链接: $PROJECT_DIR/addons/ai_engine → $ADDON_SOURCE"
echo ""

# ---------------------------------------------------------------------------
# 用 Godot 打开项目
# ---------------------------------------------------------------------------
if [ "$HAS_GODOT" = true ]; then
    step "用 Godot 打开项目..."
    open -a Godot --args --path "$PROJECT_DIR"
    echo ""
    info "Godot 正在启动，等待编辑器加载完成后："
    echo "  1. 底部面板找到 🎮 AI Engine"
    echo "  2. 输入游戏描述，例如: '做一个贪吃蛇游戏'"
    echo "  3. 按 Enter 生成游戏，按 F5 运行！"
else
    echo ""
    warn "请手动用 Godot 4.6+ 打开: $PROJECT_DIR"
fi

echo ""
